### ISSUE TITLE
Very useful tool! Can we get it to work on Mac OS?

### ISSUE THREAD

**Issue by nhippenmeyer** [riggerthegeek/pibuilder#5]

**Comment by riggerthegeek** [comment]
It's certainly my intention to make it platform agnostic. Have you tried running it on a Mac? What sort of errors did you get?

I've definitely run this on the [Fedora](https://hub.docker.com/_/fedora/) container on a Mac ok if you need to use it quickly

**Comment by nhippenmeyer** [comment]
Thanks @riggerthegeek, I was able to get this working using the Fedora docker container on my Mac.  Below is the output I get when running `sudo make build` on a mac directly:

```
sh ./scripts/pibuilder.sh
tr: Illegal byte sequence
./scripts/pibuilder.sh: line 15: md5sum: command not found
Archive:  ./cache/os..zip
  inflating: ./cache/unzip/2018-03-13-raspbian-stretch.img
./scripts/pibuilder.sh: line 84: kpartx: command not found
make: *** [build] Error 127
```

**Comment by riggerthegeek** [comment]
Ta @nhippenmeyer. If I can find the charger to my Mac, I'll have a look through it and see what's what. None of that looks too insurmountable (he says optimistically)...

**Comment by nhippenmeyer** [comment]
Sounds good @riggerthegeek. For reference, here is the Dockerfile I created (I'm generating the `settings.sh` file locally and then copying it into the docker container).  The `build.sh` script runs `make build` and then uploads the generated image to S3.

```
FROM fedora

WORKDIR /

RUN dnf -y update
RUN dnf -y install awscli git kpartx unzip

RUN git clone https://github.com/riggerthegeek/pibuilder.git

ADD . /pibuilder

WORKDIR /pibuilder

CMD ["./build.sh"]
```

**Comment by riggerthegeek** [comment]
Hey @nhippenmeyer, can you checkout the `feature/dockerfile` and see if it works on your Mac please? It works fine on my Fedora machine so I'm hopeful of it working for you.

Commands to run are:
 - `make docker-build`
 - `make setup`
 - `make build`

I seem to having a weird issue that the `make build` doesn't always work. I'll need to investigate this, but want to see if you can get it working on a Mac before I spent too much time on it

**Comment by nhippenmeyer** [comment]
First two commands work @riggerthegeek! The `make build` step fails due to a permissions error:

```bash
make docker-run CMD="sh ./scripts/pibuilder.sh"
touch settings.sh
mkdir -p ./cache
mkdir -p ./ssh-keys
docker run \
		-it \
		--privileged \
		--rm \
		-v "/Users/nhippenmeyer/src/pibuilder/settings.sh:/opt/pibuilder/settings.sh" \
		-v "/Users/nhippenmeyer/src/pibuilder/cache:/opt/pibuilder/cache" \
		-v "/Users/nhippenmeyer/src/pibuilder/ssh-keys:/ssh-keys" \
		-v "/Users/nhippenmeyer/src/pibuilder/scripts:/opt/pibuilder/scripts" \
		-u 0 \
		riggerthegeek/pibuilder \
		sh ./scripts/pibuilder.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   398    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0Warning: Failed to create the file
Warning: ./cache/os.76a0dae971f3a690a6422b6babbf2840.zip: Permission denied
  0  297M    0  2920    0     0   2920      0 29:37:35  0:00:01 29:37:34  9700
curl: (23) Failed writing body (0 != 2920)
make[1]: *** [docker-run] Error 23
make: *** [build] Error 2
```

**Comment by riggerthegeek** [comment]
Ok. Can you do the following please and tell me what you see?

```
make docker-run CMD="bash" # Should enter you into the container
echo $UID # Should read 0
ls -la /opt/pibuilder/cache # Paste the result please
touch /opt/pibuilder/cache/hello # Should create a file that syncs to your local machine when you exit
```

**Comment by nhippenmeyer** [comment]
Success! Thanks for getting this working so quickly.

**Comment by riggerthegeek** [comment]
Brilliant. I'll merge this to `master` and create a new tag. Thanks for you help
